services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Defina POSTGRES_PASSWORD no .env da raiz}
      POSTGRES_DB: ${POSTGRES_DB:-evolution}
    ports:
      - "5432:5432"

  evolution-api:
    image: atendai/evolution-api:v2.0.9
    container_name: evolution-api
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      AUTHENTICATION_API_KEY: ${EVOLUTION_API_KEY:?Defina EVOLUTION_API_KEY no .env da raiz}
      DATABASE_PROVIDER: postgresql
      DB_CONNECTION_URI: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-evolution}
